on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n depauth -g depauthb74c-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n depauth --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n depauth --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n depauth --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: depauth.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AuthenticationAPI" -f  "AuthenticationAPI/Dockerfile" -t depauth.azurecr.io/test:${{ github.sha }} --label dockerfile-path=AuthenticationAPI/Dockerfile
        docker push depauth.azurecr.io/test:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_test_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep deployauth | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace deployauth`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: deployauth
        container-registry-url: depauth.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: testdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: deployauth
        manifests: |
          manifests/deployment-5.yml
          manifests/service-5.yml
          manifests/ingress.yml
        images: |
          depauth.azurecr.io/test:${{ github.sha }}
        imagepullsecrets: |
          testdockerauth   
