on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: devdiv.azurecr.io
        username: ${{ secrets.acr_devdiv_username }}
        password: ${{ secrets.acr_devdiv_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/DailyMutualFundNAV - Final" -f  "DailyMutualFundNAV - Final/Dockerfile" -t devdiv.azurecr.io/services:${{ github.sha }} --label dockerfile-path=DailyMutualFundNAV - Final/Dockerfile
        docker push devdiv.azurecr.io/services:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_services_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep servicesbe42 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace servicesbe42`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: servicesbe42
        container-registry-url: devdiv.azurecr.io
        container-registry-username: ${{ secrets.acr_devdiv_username }}
        container-registry-password: ${{ secrets.acr_devdiv_password }}
        secret-name: servicesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: servicesbe42
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          devdiv.azurecr.io/services:${{ github.sha }}
        imagepullsecrets: |
          servicesdockerauth
